%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\vkors\Documents\R21\stateOfCharge\eq_circuit_model\FSA data endurance\endu_merge.log
%
% Auto-generated by MATLAB on 25-Jun-2020 15:36:02

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [9, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["Time", "Voltage", "Current", "Power", "Power", "VarName6", "VarName7", "VarName8"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "VarName8", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "VarName8", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("C:\Users\vkors\Documents\R21\stateOfCharge\eq_circuit_model\FSA data endurance\endu_merge.log", opts);

%% Convert to output type
Time = tbl.Time;
Voltage = tbl.Voltage;
Current = tbl.Current;
Power = tbl.Power;

%% Clear temporary variables
clear opts tbl