%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\vkors\Documents\R21\stateOfCharge\eq_circuit_model\vehicle_simulation\FSG_data\vx,current_peak,average_voltage.txt
%
% Auto-generated by MATLAB on 26-Jun-2020 12:48:08

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["timestamp", "fsgendurancebothstintsvcuINSvx", "fsgendurancebothstintsamsTSDatacurrent_peak", "fsgendurancebothstintsamsMetadataaverage_voltage_value"];
opts.VariableTypes = ["double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
tbl = readtable("C:\Users\vkors\Documents\R21\stateOfCharge\eq_circuit_model\vehicle_simulation\FSG_data\vx,current_peak,average_voltage.txt", opts);

%% Convert to output type
timestamp = tbl.timestamp;
INS_vx = tbl.fsgendurancebothstintsvcuINSvx;
current_peak = tbl.fsgendurancebothstintsamsTSDatacurrent_peak;
average_voltage = tbl.fsgendurancebothstintsamsMetadataaverage_voltage_value;

%% Clear temporary variables
clear opts tbl